#!/usr/bin/env bash

# Enforce pull before pushing
git pull

# Restrict pushing to master/main branch
branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "master" ] || [ "$branch" = "main"  ]; then
  echo "Pushing directly to '$branch' branch is not allowed."
  exit 1
fi
