#!/usr/bin/env bash

# Enforce pull before pushing
git pull

# Restrict pushing to master branch
if [ "$(git rev-parse --abbrev-ref HEAD)" = "master" ]; then
  echo 'Pushing directly to "master" branch is not allowed.'
  exit 1
fi
