#!/usr/bin/env bash

# Enforce pull before pushing
git pull

# Restrict pushing to master branch
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo 'Pushing directly to "master" branch is not allowed.'
  exit 1
fi
